/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 242620c5ffd68e4812bc9fe561c9af01)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	FIREBASE_PROJECT_ID: "tabikaigi-map";
	GROUP_ROOM: DurableObjectNamespace<import("./index").GroupRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GroupRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_ID">> {}
}
